name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    environment: release
    if: github.repository == 'kachkaev/repo-insighter'
    name: Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: .tool-versions

      - name: Install dependencies
        run: pnpm install

      - name: Verify build
        run: pnpm build

      - name: Verify lint
        run: pnpm lint

      - name: Verify bundled CLI
        run: node dist/cli.js --help

      - name: Verify tests
        run: pnpm test

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          title: Version packages
          version: pnpm changesets:version
          publish: pnpm changesets:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
